Fix bug 2553 If $prefix is not a full path, we now fail to install or uninstall before any files or directories have been created or removed.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,7 +1,7 @@
 ## Process this file with automake to produce Makefile.in	-*- makefile -*-
 #   $Source: /Users/kamil/work/gasnet-cvs2/gasnet/Makefile.am,v $
-#     $Date: 2008/10/28 05:43:37 $
-# $Revision: 1.77 $
+#     $Date: 2009/04/04 01:45:03 $
+# $Revision: 1.78 $
 # Description: Makefile for GASNet 
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt
@@ -243,6 +243,10 @@ check tests-clean:
 	@cd "$(top_builddir)/other" && $(MAKE) $@
 
 install-data-local: 
+	@if test `expr "$(prefix)" : /` = 0; then \
+          echo "ERROR: \$$prefix must begin with a '/' character."; \
+	  exit 1; \
+	 fi
 	@$(MAKE) $(recurse_local) DO_WHAT=install-data
 	@$(MAKE) recurse_special DO_WHAT=install-data
 	$(mkinstalldirs) $(DESTDIR)$(docdir)
@@ -261,9 +265,17 @@ install-data-local:
 	  fi ; \
 	done
 install-exec-local:
+	@if test `expr "$(prefix)" : /` = 0; then \
+          echo "ERROR: \$$prefix must begin with a '/' character."; \
+	  exit 1; \
+	 fi
 	@$(MAKE) $(recurse_local) DO_WHAT=install-exec
 	@$(MAKE) recurse_special DO_WHAT=install-exec
 uninstall-local: 
+	@if test `expr "$(prefix)" : /` = 0; then \
+          echo "ERROR: \$$prefix must begin with a '/' character."; \
+	  exit 1; \
+	 fi
 	@$(MAKE) $(recurse_local) DO_WHAT=uninstall
 	@$(MAKE) recurse_special DO_WHAT=uninstall
 	rm -Rf $(DESTDIR)$(docdir)
