Various makefile fixes Fix bug 533: Build testtools with the appropriate optimization CFLAGS determined by configure Fix bug 537: Infinite makefile loop Fix bug 538: Modify "gmake run-tests" to always run testtools on the frontend node This is not a perfect solution - eg it may do the "wrong thing" in situations where the frontend node has a different configuration from the compute nodes (e.g. smp vs uni), but whatever - you can always run the test by hand however you wish (gmake run-tests was not designed to be a general-purpose flexible test harness - but even with its flaws it's an improvement over the previous situation where everything had to be run manually, which still works)
Also - cleanup the line wrapping in run-tests
Add new shorthand targets for building a given test in a specific configuration - eg "gmake testsmall-par"
Misc. make portability fixes to AMMPI/AMUDP, suggested by Paul

diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -1,4 +1,4 @@
-# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/tests/Makefile.in,v 1.22 2004/03/17 18:53:27 phargrov Exp $
+# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/tests/Makefile.in,v 1.23 2004/03/18 12:07:35 bonachea Exp $
 # Description: Makefile for GASNet tests
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt
@@ -82,51 +82,70 @@ testprograms_err =      \
         testhsl         \
 	$(MPI_TEST)
 
+# tests that do not link libgasnet and should execute directly on the frontend with no spawner
+testprograms_nongasnet = \
+	testtools
+
 CONDUIT_NAME_UC=`echo $(CONDUIT_NAME) | @AWK@  '{print toupper($$0)}'`
-run-tests:
-	@$(TEST_PARAMS)                                                                                                                                                \
-	export `echo "$(TEST_PARAMS)" | @AWK@ 'BEGIN {FS="=";RS=";"}{ print $$1 }'` ;                                                                                  \
-	tests_to_run="" export tests_to_run ;                                                                                                                          \
-	tests_to_ignore="" export tests_to_ignore ;                                                                                                                    \
-	for file in $(testprograms) ; do if test -x "$$file" ; then                                                                                                    \
-	  if test "`echo \"$(testprograms_err)\"| grep $$file ; exit 0`"; then                                                                                         \
-	    tests_to_ignore="$$tests_to_ignore $$file" export tests_to_ignore ;                                                                                        \
-	  else                                                                                                                                                         \
-	    tests_to_run="$$tests_to_run $$file" export tests_to_run ;                                                                                                 \
-	  fi ;                                                                                                                                                         \
-	fi ; done ;                                                                                                                                                    \
-	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" ;                                                                           \
-	echo " Running $(CONDUIT_NAME)-conduit tests:                                    " ;                                                                           \
-	for file in $$tests_to_run ; do echo "   $$file" ; done ;                                                                                                      \
-	if test "$$tests_to_ignore" ; then                                                                                                                             \
-	  echo " Ignoring tests: $$tests_to_ignore" ;                                                                                                                  \
-	fi ;                                                                                                                                                           \
-	echo " If this fails to spawn a job, you may need to re-run with a command like: " ;                                                                           \
-	echo "  gmake run-tests $(CONDUIT_NAME_UC)_RUNCMD=\"$(CONDUIT_RUNCMD)\"" ;                                                                                     \
-	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" ;                                                                           \
-	TEST_RUNCMD="$$$(CONDUIT_NAME_UC)_RUNCMD" export TEST_RUNCMD ;                                                                                                 \
-	TEST_RUNCMD="`eval echo $$TEST_RUNCMD`" export TEST_RUNCMD ;                                                                                                   \
-	if test -z "$$TEST_RUNCMD" ; then                                                                                                                              \
-	  TEST_RUNCMD="$(CONDUIT_RUNCMD)" export TEST_RUNCMD ;                                                                                                         \
-	fi ;                                                                                                                                                           \
-	for file in $$tests_to_run ; do                                                                                                                                \
-	    threadmode=`cat $$file@EXESUFFIX@ | @AWK@ 'BEGIN {FS=" ";RS="$$"} /GASNetThreadModel: [^ ]* / { split($$2,A,/_/); print A[2] ; exit}'` export threadmode ; \
-	    echo "*** Running $(CONDUIT_NAME)-conduit $$file in $$threadmode/$(GASNET_SEGMENT_STR) mode ***" ;                                                         \
-	    args="$$""$${file}_args" ;                                                                                                                                 \
-	    args="`eval echo $$args`" ;                                                                                                                                \
-	    nodes="$$\{""$${file}_nodes-$(TEST_NODES)\}" ;                                                                                                             \
-	    nodes="`eval eval echo $$nodes`" ;                                                                                                                         \
-	    cmd="`echo \"$$TEST_RUNCMD\" | @AWK@ '{ gsub(\"%P\",\"./'$$file'\"); gsub(\"%N\",\"'$$nodes'\"); gsub(\"%A\",\"'"$$args"'\"); print $0 }'`" export cmd;    \
-	    echo "$$cmd" ;                                                                                                                                             \
-	    /usr/bin/time $$cmd || echo "ERROR: Test exited with failure code=$$?" ;                                                                                   \
-	    echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" ;                                                                       \
-	done ;                                                                                                                                                         \
+run-tests: force
+	@$(TEST_PARAMS)                                                                 \
+	export `echo "$(TEST_PARAMS)" | @AWK@ 'BEGIN {FS="=";RS=";"}{ print $$1 }'` ;   \
+	line='+++++++++++++++++++++++++++++++++++++++' ; line="$$line$$line" ;          \
+	tests_to_run="" export tests_to_run ;                                           \
+	tests_to_ignore="" export tests_to_ignore ;                                     \
+	for file in $(testprograms) ; do if test -x "$$file" ; then                     \
+	  if test "`echo \"$(testprograms_err)\"| grep $$file ; exit 0`"; then          \
+	    tests_to_ignore="$$tests_to_ignore $$file" ;                                \
+	  else                                                                          \
+	    tests_to_run="$$tests_to_run $$file" ;                                      \
+	  fi ;                                                                          \
+	fi ; done ;                                                                     \
+	echo $$line ;                                                                   \
+	echo " Running $(CONDUIT_NAME)-conduit tests:" ;                                \
+	for file in $$tests_to_run ; do echo "   $$file" ; done ;                       \
+	if test "$$tests_to_ignore" ; then                                              \
+	  echo " Ignoring tests: $$tests_to_ignore" ;                                   \
+	fi ;                                                                            \
+	echo " If this fails to spawn a job,"                                           \
+	     "you may need to re-run with a command like:" ;                            \
+	echo "  gmake run-tests $(CONDUIT_NAME_UC)_RUNCMD=\"$(CONDUIT_RUNCMD)\"" ;      \
+	echo $$line ;                                                                   \
+	TEST_RUNCMD="$$$(CONDUIT_NAME_UC)_RUNCMD" export TEST_RUNCMD ;                  \
+	TEST_RUNCMD="`eval echo $$TEST_RUNCMD`" ;                                       \
+	if test -z "$$TEST_RUNCMD" ; then                                               \
+	  TEST_RUNCMD="$(CONDUIT_RUNCMD)" ;                                             \
+	fi ;                                                                            \
+	for file in $$tests_to_run ; do                                                 \
+	    args="$$""$${file}_args" ;                                                  \
+	    args="`eval echo $$args`" ;                                                 \
+	    nodes="$$\{""$${file}_nodes-$(TEST_NODES)\}" ;                              \
+	    nodes="`eval eval echo $$nodes`" ;                                          \
+	    if test "`echo \"$(testprograms_nongasnet)\"| grep $$file ; exit 0`"; then  \
+	      echo "*** Running $(CONDUIT_NAME)-conduit $$file ***" ;                   \
+	      cmd="./$$file $$args" ;                                                   \
+	    else                                                                        \
+	      awk_threadscan='BEGIN {FS=" ";RS="$$"}                                    \
+		/GASNetThreadModel: [^ ]* / { split($$2,A,/_/); print A[2] ; exit}' ;   \
+	      threadmode=`cat -v $$file@EXESUFFIX@ | eval @AWK@ \'$$awk_threadscan\'` ; \
+	      echo "*** Running $(CONDUIT_NAME)-conduit $$file"                         \
+		   "in $$threadmode/$(GASNET_SEGMENT_STR) mode ***" ;                   \
+	      awk_cmdbuild='{ gsub("%P","./'$$file'");                                  \
+			      gsub("%N","'$$nodes'");                                   \
+			      gsub("%A","'"$$args"'"); print $0 }' ;                    \
+	      cmd="`echo \"$$TEST_RUNCMD\" | eval @AWK@ \'$$awk_cmdbuild\'`" ;          \
+	    fi;                                                                         \
+	    echo "$$cmd" ;                                                              \
+	    /usr/bin/time $$cmd || echo "ERROR: Test exited with failure code=$$?" ;    \
+	    echo $$line ;                                                               \
+	done ;                                                                          \
 	echo "TESTS COMPLETE"
 
 # testtools is a special minimal case for an app that just uses GASNet tools
+# specifically, we carefully omit BUILDCONFIG_DEFINES
 testtools: force
-	@CC@ @MISC_CFLAGS@ $(GASNET_INCLUDES) @GASNET_THREAD_DEFINES@ -DHAVE_PTHREAD_H -c -o $@.o $(srcdir)/$@.c
-	@CC@ -o $@ $@.o @GASNET_THREAD_LIBS@ @LIBS@ @LIBM@
+	@CC@ @CFLAGS@ @MISC_CFLAGS@ @MISC_CPPFLAGS@ $(GASNET_INCLUDES) @GASNET_THREAD_DEFINES@ -DHAVE_PTHREAD_H -c -o $@.o $(srcdir)/$@.c
+	@CC@ @CFLAGS@ @MISC_CFLAGS@ -o $@ $@.o @GASNET_THREAD_LIBS@ @LIBS@ @LIBM@
+	rm -f $@.o
 
 # some tests need delay.o
 testlogGP: delay.o
@@ -142,12 +161,13 @@ delay.o: force
 testmpi: force
 	@MPI_CC@ -I$(srcdir) $(GASNET_CPPFLAGS) $(GASNET_CFLAGS) @MPI_CFLAGS@ -c -o $@.o $(srcdir)/$@.c
 	$(GASNET_MPI_LD) $(GASNET_LDFLAGS) @MPI_CFLAGS@ -o $@ $@.o @MPI_LIBS@ $(GASNET_LIBS)
-	
+	rm -f $@.o	
 
 # This is a model for how GASNet clients should be built:
 test% : force
 	$(GASNET_CC) -I$(srcdir) $(GASNET_CPPFLAGS) $(GASNET_CFLAGS) -c -o $@.o $(srcdir)/$@.c
 	$(GASNET_LD) $(GASNET_LDFLAGS) -o $@ $@.o $($@_extraobjs) $(GASNET_LIBS)
+	rm -f $@.o
 
 force:
 	
