add configure detections of /usr/bin/time and /usr/bin/env
CVSMAIL: CC:

diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -1,6 +1,6 @@
 #   $Source: /Users/kamil/work/gasnet-cvs2/gasnet/tests/Makefile.in,v $
-#     $Date: 2005/02/04 14:19:16 $
-# $Revision: 1.46 $
+#     $Date: 2005/02/05 03:32:51 $
+# $Revision: 1.47 $
 # Description: Makefile for GASNet tests
 # @configure_input@
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
@@ -137,6 +137,9 @@ run-tests: force
 	if test -z "$$TEST_RUNCMD" ; then                                               \
 	  TEST_RUNCMD="$(CONDUIT_RUNCMD)" ;                                             \
 	fi ;                                                                            \
+	if test -z "$$TIMECMD" ; then                                                   \
+	  TIMECMD="@TIMECMD@" ;                                                         \
+	fi ;                                                                            \
 	for file in $$tests_to_run ; do                                                 \
 	    args="$$""$${file}_args" ;                                                  \
 	    args="`eval echo $$args`" ;                                                 \
@@ -155,7 +158,7 @@ run-tests: force
 	    fi;                                                                         \
 	    echo "$$cmd" ;                                                              \
 	    env DUMMYVAL=1 $(TEST_ENV)                                                  \
-	    /usr/bin/time $$cmd || echo "ERROR: Test exited with failure code=$$?" ;    \
+	    $$TIMECMD $$cmd || echo "ERROR: Test exited with failure code=$$?" ;        \
 	    echo $$line ;                                                               \
 	done ;                                                                          \
 	echo "TESTS COMPLETE"
