Initial round of UPC/GASNet porting work for BG/L
General improvements to the way we run GASNet tests under cross compilation
Most of effort was in the spawn scripts and Makefile goop, coping with the horrible interface on their mpirun program. However, it turns out mpirun is incompatible with the resource manager on the Argonne machine and causes other users job to crash, so we cannot even safely use it, at least at this site. We currently have no way to run interactive jobs on the machine, which is going to make it nearly impossible for me to make further progress on debugging this port until it's resolved.

Status overview:
gcc/debug: GASNet & UPC build and work  - all the GASNet tests pass except for a minor testenv failure and a memory exhaustion crash in testlarge.
xlc/debug: GASNet & UPC build - all the GASNet tests pass except for the same failures. UPC applications still cannot be built due to some problems with the gcc-as-xlc preprocessor hack, which requires further tweaking for cross-compilation.

gcc/ndebug: still has correctness problems that prevent any jobs from running - this may simply be due to the known bugs in the gcc 3.2 optimizer, but in any case I don't yet have any performance numbers I can trust.
xlc/ndebug: not yet tried.

Disable MALLOC_CHECK_ on Blue Gene, because it breaks blrts
Implement native timers for PPC-Linux/XLC
Change all instances of #ifdef LINUX to #ifdef __linux__
Fix a confusing typo in debug malloc out-of-mem error message
Tweak AMMPI/AMUDP handler-run macros to improve codegen.
Fix AMMPI/AMUDP bug in payload alignment of loopback mediums, that for some reason hasn't shown up elsewhere.
Remove some unnecessary MPI_Buffer_attach/detach calls from various mpi testers.

CVSMAIL: CC: ihaque@eecs.berkeley.edu

diff --git a/other/ammpi/Makefile.tests b/other/ammpi/Makefile.tests
--- a/other/ammpi/Makefile.tests
+++ b/other/ammpi/Makefile.tests
@@ -5,14 +5,15 @@ TEST_LINE=++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 AMMPI_RUNCMD_EXP=\
       TEST_RUN_P=`echo "$$TEST_RUN" | sed 's/ .*$$//'`  \
       TEST_RUN_A=`echo "$$TEST_RUN" | sed 's/^[^ ]* //'` \
-      TEST_DOIT=`echo $(AMMPI_RUNCMD) | sed 's/%N/$(TEST_NODES)/;s@%C@'"$$TEST_RUN"'@;s@%P@'"$$TEST_RUN_P"'@;s@%A@'"$$TEST_RUN_A"'@;s/%V//'`
+      TEST_RUN_D=`pwd` \
+      TEST_DOIT=`echo $(AMMPI_RUNCMD) | sed 's/%N/$(TEST_NODES)/;s@%C@'"$$TEST_RUN"'@;s@%P@'"$$TEST_RUN_P"'@;s@%A@'"$$TEST_RUN_A"'@;s@%D@'"$$TEST_RUN_D"'@;s/%V//'`
 TEST_RUNCMD=$(AMMPI_RUNCMD_EXP) ; 				\
 	 testname=`basename $$TEST_RUN_P` ;                     \
 	 faildesc="ammpi/$$testname" ;                          \
          if test -x "$$TEST_RUN_P" ; then                       \
             echo "  **** $$testname **** "; 	                \
             echo $$TEST_DOIT ; 					\
-            ( $$TEST_DOIT || echo "ERROR: Test exited with failure code=$$?" 2>&1 ) | tee .test-output ; \
+            ( eval $$TEST_DOIT || echo "ERROR: Test exited with failure code=$$?" 2>&1 ) | tee .test-output ; \
             failure=`grep -e ERROR -e 'fatal signal' .test-output` ;                    \
             if test "$$failure" != "" ; then                                            \
                echo " " >> $(TESTLOG) ;                                                 \
diff --git a/other/amudp/Makefile.tests b/other/amudp/Makefile.tests
--- a/other/amudp/Makefile.tests
+++ b/other/amudp/Makefile.tests
@@ -11,7 +11,7 @@ TEST_RUNCMD=$(AMUDP_RUNCMD_EXP) ; 				\
          if test -x "$$TEST_RUN_P" ; then                       \
             echo "  **** $$testname **** "; 	                \
             echo $$TEST_DOIT ; 					\
-            ( $$TEST_DOIT || echo "ERROR: Test exited with failure code=$$?" 2>&1 ) | tee .test-output ; \
+            ( eval $$TEST_DOIT || echo "ERROR: Test exited with failure code=$$?" 2>&1 ) | tee .test-output ; \
             failure=`grep -e ERROR -e 'fatal signal' .test-output` ;                    \
             if test "$$failure" != "" ; then                                            \
                echo " " >> $(TESTLOG) ;                                                 \
